version: '3.8'

networks: 
  repoadopt:
    name: repoadopt
    driver: bridge

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: kong-db
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks: 
      - repoadopt
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong

  kong:
    image: docker.io/bitnami/kong:2
    container_name: kong
    ports:
      - 8100:8000
      - 8101:8001
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
    networks: 
      - repoadopt

  repoadopt-client:
    image: repoadopt/client:develop
    container_name: repoadopt-client
    networks: 
      - repoadopt
    volumes:
      - .:/public
    environment:
      CONFIGJS: |
          window.config = (() => {
            return {
              VUE_APP_GRAPHQL: "http://$MACHINE_URL:8100",
              VUE_APP_AXIOS: "http://$MACHINE_URL:8100",
              VUE_APP_PAGINATION_LIMIT: 10,
              VUE_APP_CLIENT_ID: "$CLIENT_ID",
            };
          })();
      CONTAINER_URL: repoadopt-client.repoadopt:80
    entrypoint: /bin/sh
    volumes: 
      - ./register_nginx.sh:/register_nginx.sh
      - .:/public
    command: -c "echo \"$$CONFIGJS\" > /repoadopt/app/config.js; chmod +x ./register_nginx.sh; ./register_nginx.sh; nginx -g \"daemon off;\""
    depends_on:
      - kong
      - repoadopt-graphql
      - repoadopt-authentication

  repoadopt-mongodb:
    image: bitnami/mongodb
    container_name: repoadopt-mongodb
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks: 
      - repoadopt

  repoadopt-graphql:
    image: repoadopt/graphql:develop
    container_name: repoadopt-graphql
    environment:
      - HOST=mongodb://repoadopt-mongodb.repoadopt/
      - DBHOST=27017
      - PORT=81
      - ENVIRONMENT=deploy
      - GATEWAY=kong.repoadopt:8001
      - GRAPHQL_URL=repoadopt-graphql.repoadopt:81
      - GATEWAY_RETRIES=20
    networks: 
      - repoadopt
    depends_on:
      - repoadopt-mongodb
      - kong

  repoadopt-authentication:
    image: repoadopt/authentication:develop
    container_name: repoadopt-authentication
    command: bash -c "python ./security/pem_keys.py && python main.py"
    environment:
      - CLIENT_SECRET=$CLIENT_SECRET
      - PORT=82
      - DEVELOPMENT=True
      - ISSUER=RepoAdopt
      - TOKEN_EXPIRATION_TIME=604800
      - GATEWAY=kong.repoadopt:8001
      - AUTHENTICATION_URL=repoadopt-authentication.repoadopt:82
      - GATEWAY_RETRIES=20
    networks: 
      - repoadopt
    depends_on: 
      - kong

volumes:
  postgresql_data:
    driver: local
