version: '3.8'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: repoadopt-postgresql
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong

  kong:
    image: docker.io/bitnami/kong:2
    container_name: kong
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami

  repoadopt-client:
    image: repoadopt/client:develop
    container_name: repoadopt-client
    expose:
      - 8080
    ports:
      - '8080:80'
    depends_on:
      - repoadopt-graphql
      - repoadopt-authentication

  repoadopt-mongodb:
    image: bitnami/mongodb
    container_name: repoadopt-mongodb
    expose:
      - 27017
    ports:
      - '27017:27017'

  repoadopt-graphql:
    image: repoadopt/graphql:develop
    container_name: repoadopt-graphql
    environment:
      - HOST=mongodb://repoadopt-mongodb/
      - DBHOST=27017
      - PORT=80
      - ENVIRONMENT=deploy
    expose:
      - 5000
    ports:
      - '5000:80'
    depends_on:
      - repoadopt-mongodb

  repoadopt-authentication:
    image: repoadopt/authentication:develop
    container_name: repoadopt-authentication
    command: bash -c "python ./security/pem_keys.py && python main.py"
    environment:
      - CLIENT_SECRET=3af7485a98304553846c9687d07d011ebc2a413d
      - PORT=80
      - DEVELOPMENT=True
      - ISSUER=RepoAdopt
      - TOKEN_EXPIRATION_TIME=604800
    expose:
      - 5001
    ports:
      - '5001:80'

volumes:
  postgresql_data:
    driver: local
