version: '3.8'

networks: 
  repoadopt:
    name: repoadopt
    driver: bridge

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: kong-db
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks: 
      - repoadopt
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong

  kong:
    image: docker.io/bitnami/kong:2
    container_name: kong
    ports:
      - 8100:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
    networks: 
      - repoadopt

  repoadopt-client:
    image: repoadopt/client:develop
    container_name: repoadopt-client
    expose:
      - 8080
    ports:
      - '8080:80'
    networks: 
      - repoadopt
    depends_on:
      - repoadopt-graphql
      - repoadopt-authentication

  repoadopt-mongodb:
    image: bitnami/mongodb
    container_name: repoadopt-mongodb
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks: 
      - repoadopt

  repoadopt-graphql:
    image: repoadopt/graphql:dynamic_routes
    container_name: repoadopt-graphql
    environment:
      - HOST=mongodb://repoadopt-mongodb.repoadopt/
      - DBHOST=27017
      - PORT=81
      - ENVIRONMENT=deploy
      - GATEWAY=kong.repoadopt:8001
      - GRAPHQL_URL=http://repoadopt-graphql:81/graphql
    networks: 
      - repoadopt
    depends_on:
      - repoadopt-mongodb
      - kong

  repoadopt-authentication:
    image: repoadopt/authentication:dynamic_routes
    container_name: repoadopt-authentication
    command: bash -c "python ./security/pem_keys.py && python main.py"
    environment:
      - CLIENT_SECRET=3af7485a98304553846c9687d07d011ebc2a413d
      - PORT=82
      - DEVELOPMENT=True
      - ISSUER=RepoAdopt
      - TOKEN_EXPIRATION_TIME=604800
      - GATEWAY=kong.repoadopt:8001
      - GRAPHQL_URL=http://repoadopt-authenticationl:82/signin
    networks: 
      - repoadopt
    depends_on: 
      - kong
    expose:
      - 5001
    ports:
      - '5001:82'

volumes:
  postgresql_data:
    driver: local
